# Generated by Django 3.1.7 on 2021-06-24 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0002_auto_20210624_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='comission',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='product_price',
        ),
    ]
