# Generated by Django 3.1.7 on 2021-06-24 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0003_auto_20210624_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('comission', models.FloatField()),
                ('sellerp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sells', to='useraccounts.sellerprofile')),
            ],
        ),
    ]
