# Generated by Django 3.1.7 on 2021-06-28 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0004_sell'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='Alevel',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sell',
            name='Blevel',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sell',
            name='Clevel',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sell',
            name='Dlevel',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
